name: style_cron_job
description: Style Cron Job is periodic operations executor and definator with basic syntax. You can define a period and run your process with your own executor or through the controller.
version: 1.0.4+3
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style_cron_job
repository: https://github.com/Mehmetyaz/style

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.7.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.21.1
