name: style_test
description: A starting point for Dart libraries or applications.
version: 1.0.0+3
homepage: https://github.com/Mehmetyaz/style/tree/main/packages/style_test/
repository: https://github.com/Mehmetyaz/style

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  test: ^1.21.1
  meta: ^1.7.0
  style_dart: ^1.0.2+8

dev_dependencies:
  effective_dart: ^1.3.2

