name: style_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-85.0.dev <3.0.0'


dependencies:
  meta: ^1.7.0
  http: ^0.13.4
#   path: ^1.8.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.20.1
